spring:
  application:
    name: fitlab
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fitlab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS